### ISSUE TITLE
✨ Add progress bar to CLI fetch

### ISSUE THREAD

**Issue by antonsmithnz** [firebrandhq/silverstripe-hail#11]
This has been needed for a long time, especially with larger Hail organisations with lots of objects.

The current CLI output looks like this. Not nice.
```
Running Task HailFetchTask

Fetching HailArticleFetching HailImageFetching HailPublicationFetching HailTagFe
```

We should change it to something like this. Add colors too, why not, and maybe a verbose param so we can see exactly what is being processed.

```
Running Task HailFetchTask...

Fetching HailArticle...
[====================] 100% (400 of 400)

Fetching HailImage...
[==========__________]  50% (60 of 120)

```

Whatever is built will need to play nice with cron jobs, more so if the output is emailed once the job is done.

**Comment by maxime-rainville** [comment]
I would suggest you have a look at `symfony/console`. It makes a lot of those processes like adding progress bars and adding pretty colours to your output a breeze.

**Comment by antonsmithnz** [comment]
Ta, thanks for that @maxime-rainville - I was trying to find this yesterday.

**Comment by maxime-rainville** [comment]
We're thinking about refactoring our own build task around it at some stage. https://github.com/silverstripe/silverstripe-framework/issues/5542

**Comment by antonsmithnz** [comment]
Awesome, I would be very keen for this to happen!

**Comment by marc-firebrand** [comment]
Added:
SS3 (6d5b118ae97f40bfafef81d451f0913edb33f277) 
SS4 (e77d25cb7ec1f932310d16455e46aca26c799564)
